//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string Features { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string MLSNumber { get; set; }
        public string Price { get; set; }
        public int Bedrooms { get; set; }
        public int Bathrooms { get; set; }
        public string LotArea { get; set; }
        public string FloorArea { get; set; }
        public int Age { get; set; }
        public string MoreInfoLink { get; set; }
        public int Status { get; set; }
        public string VideoLink { get; set; }
        public Nullable<int> DealYear { get; set; }
    
        public virtual ListingCN ListingCN { get; set; }
    }
}
