//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingCN
    {
        public int ListingId { get; set; }
        public string Description { get; set; }
        public string Features { get; set; }
        public string City { get; set; }
    
        public virtual Listing Listing { get; set; }
    }
}
